name: Deploy to GitHub Pages

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on: 
  push:
    branches: [ 'main' ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run production

      - name: Prepare output
        run: |
          mkdir deploy
          mkdir deploy/dist
          mv dist/* deploy/dist
          mv index.html deploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: avalon.school.nz
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: deploy/
          

